# version: "3"

# services:
#   web:
#     image: nginx:latest
#     ports:
#       - "8080:80"
#     volumes:
#       - ./website:/var/www/html
#       - ./default.conf:/etc/nginx/conf.d/default.conf
#     links:
#       - php-fpm
#   php-fpm:
#     image: php:8.1-fpm
#     build:
#       context: .
#       dockerfile: Dockerfile
#     volumes:
#       - ./website:/var/www/html

version: "3"

networks:
  proxynetwork:
    external: true

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./website:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    depends_on:
      - php-fpm
      - mariadb
    networks:
      - proxynetwork

  php-fpm:
    image: php:8.1-fpm
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./website:/var/www/html
    depends_on:
      - mariadb
    networks:
      - proxynetwork

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: random_password
      MYSQL_DATABASE: webtoolshive
      MYSQL_USER: muqeet
      MYSQL_PASSWORD: "12345678"
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - proxynetwork
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: random_password
    ports:
      - "8081:80"
    networks:
      - proxynetwork
